### ISSUE TITLE
Must have a updateEventCounter?

### ISSUE THREAD

**Issue by TiagoGouvea** [jfuentesa/gengamification#1]
On executeEvent it call increaseEventCounter, that insert a new record to _events table, but, I think it must insert one time, and after that must increase the eventcounter field... I'm right?

**Comment by TiagoGouvea** [comment]
Ops... ok. The events table must have a unique key in id_user and id_event. Solved.

What about put a sql creation file on repository? 

:)

Thanks

**Comment by jfuentesa** [comment]
Updated, sorry.

**Comment by TiagoGouvea** [comment]
Thanks!
